/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.shopnow.dto;

public class RestResponse {
	private java.lang.String[] messages;

 	public void setMessages(java.lang.String[] messages) {
		this.messages = messages;
	}

	public java.lang.String[] getMessages() {
		return messages;
	}

	private ResultElement[] result;

 	public void setResult(ResultElement[] result) {
		this.result = result;
	}

	public ResultElement[] getResult() {
		return result;
	}

}