/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.shopnow.dto;

public class ResultElement {
	private java.lang.String abbr;

 	public void setAbbr(java.lang.String abbr) {
		this.abbr = abbr;
	}

	public java.lang.String getAbbr() {
		return abbr;
	}

	private java.lang.String capital;

 	public void setCapital(java.lang.String capital) {
		this.capital = capital;
	}

	public java.lang.String getCapital() {
		return capital;
	}

	private java.lang.String country;

 	public void setCountry(java.lang.String country) {
		this.country = country;
	}

	public java.lang.String getCountry() {
		return country;
	}

	private java.lang.String largest_city;

 	public void setLargest_city(java.lang.String largest_city) {
		this.largest_city = largest_city;
	}

	public java.lang.String getLargest_city() {
		return largest_city;
	}

	private java.lang.String area;

 	public void setArea(java.lang.String area) {
		this.area = area;
	}

	public java.lang.String getArea() {
		return area;
	}

	private java.lang.String name;

 	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getName() {
		return name;
	}

}