/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.shopnow.dto;

import com.fasterxml.jackson.annotation.JsonCreator;

public class Test {
	private RestResponse RestResponse;

	@JsonCreator
 	public Test() {
		super();
		// TODO Auto-generated constructor stub
	}

	public RestResponse getRestResponse() {
		return this.RestResponse;
	}

	public void setRestResponse(RestResponse restResponse) {
		this.RestResponse = restResponse;
	}

	
}