/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.shopnow.dto;

import com.fasterxml.jackson.annotation.JsonCreator;

public class Test {
	private RestResponse restresponse;

	@JsonCreator
 	public Test() {
		super();
		// TODO Auto-generated constructor stub
	}

	public void setRestresponse(RestResponse restresponse) {
		this.restresponse = restresponse;
	}

	public RestResponse getRestresponse() {
		return restresponse;
	}

}